"""add customer id to location logs

Revision ID: 2e837c7e7fe9
Revises: b79a4d6bb2cc
Create Date: 2026-09-09 12:21:18.910214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e837c7e7fe9'
down_revision: Union[str, None] = 'b79a4d6bb2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_logs', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_location_logs_customer_id'), 'location_logs', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'location_logs', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location_logs', type_='foreignkey')
    op.drop_index(op.f('ix_location_logs_customer_id'), table_name='location_logs')
    op.drop_column('location_logs', 'customer_id')
    # ### end Alembic commands ###
