"""add purchase orders and evidence policy

Revision ID: 4c87416f8a3e
Revises: 2e837c7e7fe9
Create Date: 2026-09-10 09:32:58.576455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c87416f8a3e'
down_revision: Union[str, None] = '2e837c7e7fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('purchase_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extracted_json', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_documents_id'), 'purchase_documents', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_documents_purchase_order_id'), 'purchase_documents', ['purchase_order_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_product_id'), 'purchase_order_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.add_column('inventory_receipt_lines', sa.Column('purchase_order_line_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_receipt_lines_purchase_order_line_id'), 'inventory_receipt_lines', ['purchase_order_line_id'], unique=False)
    op.create_foreign_key(None, 'inventory_receipt_lines', 'purchase_order_lines', ['purchase_order_line_id'], ['id'])
    op.add_column('inventory_receipts', sa.Column('purchase_order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_receipts_purchase_order_id'), 'inventory_receipts', ['purchase_order_id'], unique=False)
    op.create_foreign_key(None, 'inventory_receipts', 'purchase_orders', ['purchase_order_id'], ['id'])
    op.add_column('products', sa.Column('evidence_policy', sa.String(length=20), nullable=True))
    op.execute("UPDATE products SET evidence_policy = 'RECEIPT' WHERE evidence_policy IS NULL")
    op.alter_column('products', 'evidence_policy', existing_type=sa.String(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'evidence_policy')
    op.drop_constraint(None, 'inventory_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_receipts_purchase_order_id'), table_name='inventory_receipts')
    op.drop_column('inventory_receipts', 'purchase_order_id')
    op.drop_constraint(None, 'inventory_receipt_lines', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_receipt_lines_purchase_order_line_id'), table_name='inventory_receipt_lines')
    op.drop_column('inventory_receipt_lines', 'purchase_order_line_id')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_product_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_documents_purchase_order_id'), table_name='purchase_documents')
    op.drop_index(op.f('ix_purchase_documents_id'), table_name='purchase_documents')
    op.drop_table('purchase_documents')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
