"""add inventory model to products

Revision ID: 7e1ffe48c905
Revises: 4c87416f8a3e
Create Date: 2026-09-11 09:12:40.941094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1ffe48c905'
down_revision: Union[str, None] = '4c87416f8a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('inventory_model', sa.String(length=20), nullable=True))
    op.execute("UPDATE products SET inventory_model = 'SERIALIZED' WHERE lower(coalesce(category,'')) IN ('equipment','spare parts')")
    op.execute("UPDATE products SET inventory_model = 'BULK' WHERE inventory_model IS NULL")
    op.alter_column('products', 'inventory_model', existing_type=sa.String(length=20), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'inventory_model')
    # ### end Alembic commands ###
