"""add staff operations tables and order tax fields

Revision ID: 918376afb222
Revises: 001_initial
Create Date: 2026-09-08 15:24:46.682781

Aligns databases that were bootstrapped via Base.metadata.create_all()
with the current model metadata. On a fresh database, start the app once
(create_all builds all tables), then run `alembic stamp head`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '918376afb222'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_orders_delivery_address_id_fkey', 'sales_orders', type_='foreignkey')
    op.drop_constraint('sales_orders_contact_id_fkey', 'sales_orders', type_='foreignkey')
    op.create_foreign_key('sales_orders_delivery_address_id_fkey', 'sales_orders', 'sales_customer_addresses', ['delivery_address_id'], ['id'])
    op.create_foreign_key('sales_orders_contact_id_fkey', 'sales_orders', 'sales_customer_contacts', ['contact_id'], ['id'])
    if _table_exists('customer_contacts'):
        op.drop_table('customer_contacts')
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_unique_constraint('uq_brand_normalized', 'brands', ['normalized_name'])
    op.create_index(op.f('ix_location_logs_id'), 'location_logs', ['id'], unique=False)
    op.create_index(op.f('ix_order_template_items_id'), 'order_template_items', ['id'], unique=False)
    op.alter_column('order_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_order_templates_id'), 'order_templates', ['id'], unique=False)
    op.create_index(op.f('ix_order_templates_salesman_id'), 'order_templates', ['salesman_id'], unique=False)
    op.drop_constraint('product_barcodes_barcode_value_key', 'product_barcodes', type_='unique')
    op.create_index(op.f('ix_product_barcodes_barcode_value'), 'product_barcodes', ['barcode_value'], unique=False)
    op.create_index(op.f('ix_product_barcodes_id'), 'product_barcodes', ['id'], unique=False)
    op.create_index(op.f('ix_product_barcodes_product_id'), 'product_barcodes', ['product_id'], unique=False)
    op.create_unique_constraint('uq_barcode_value', 'product_barcodes', ['barcode_value'])
    op.drop_constraint('product_intake_requests_request_number_key', 'product_intake_requests', type_='unique')
    op.create_index(op.f('ix_product_intake_requests_barcode_value'), 'product_intake_requests', ['barcode_value'], unique=False)
    op.create_index(op.f('ix_product_intake_requests_id'), 'product_intake_requests', ['id'], unique=False)
    op.create_index(op.f('ix_product_intake_requests_request_number'), 'product_intake_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_product_unit_images_id'), 'product_unit_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_unit_images_product_unit_id'), 'product_unit_images', ['product_unit_id'], unique=False)
    op.drop_constraint('product_units_serial_number_key', 'product_units', type_='unique')
    op.create_index(op.f('ix_product_units_barcode'), 'product_units', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_units_id'), 'product_units', ['id'], unique=False)
    op.create_index(op.f('ix_product_units_product_id'), 'product_units', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_units_serial_number'), 'product_units', ['serial_number'], unique=True)
    op.create_index(op.f('ix_sales_customer_addresses_customer_id'), 'sales_customer_addresses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_addresses_id'), 'sales_customer_addresses', ['id'], unique=False)
    op.drop_constraint('sales_customer_addresses_customer_id_fkey', 'sales_customer_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'sales_customer_addresses', 'customers', ['customer_id'], ['id'])
    op.create_index(op.f('ix_sales_customer_contacts_customer_id'), 'sales_customer_contacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_contacts_id'), 'sales_customer_contacts', ['id'], unique=False)
    op.drop_constraint('sales_customer_contacts_customer_id_fkey', 'sales_customer_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'sales_customer_contacts', 'customers', ['customer_id'], ['id'])
    op.drop_constraint('tax_profiles_code_key', 'tax_profiles', type_='unique')
    op.create_index(op.f('ix_tax_profiles_code'), 'tax_profiles', ['code'], unique=True)
    op.create_index(op.f('ix_tax_profiles_id'), 'tax_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_profiles_id'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_code'), table_name='tax_profiles')
    op.create_unique_constraint('tax_profiles_code_key', 'tax_profiles', ['code'])
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_foreign_key('sales_orders_contact_id_fkey', 'sales_orders', 'customer_contacts', ['contact_id'], ['id'])
    op.create_foreign_key('sales_orders_delivery_address_id_fkey', 'sales_orders', 'customer_addresses', ['delivery_address_id'], ['id'])
    op.drop_constraint(None, 'sales_customer_contacts', type_='foreignkey')
    op.create_foreign_key('sales_customer_contacts_customer_id_fkey', 'sales_customer_contacts', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sales_customer_contacts_id'), table_name='sales_customer_contacts')
    op.drop_index(op.f('ix_sales_customer_contacts_customer_id'), table_name='sales_customer_contacts')
    op.drop_constraint(None, 'sales_customer_addresses', type_='foreignkey')
    op.create_foreign_key('sales_customer_addresses_customer_id_fkey', 'sales_customer_addresses', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sales_customer_addresses_id'), table_name='sales_customer_addresses')
    op.drop_index(op.f('ix_sales_customer_addresses_customer_id'), table_name='sales_customer_addresses')
    op.drop_index(op.f('ix_product_units_serial_number'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_product_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_barcode'), table_name='product_units')
    op.create_unique_constraint('product_units_serial_number_key', 'product_units', ['serial_number'])
    op.drop_index(op.f('ix_product_unit_images_product_unit_id'), table_name='product_unit_images')
    op.drop_index(op.f('ix_product_unit_images_id'), table_name='product_unit_images')
    op.drop_index(op.f('ix_product_intake_requests_request_number'), table_name='product_intake_requests')
    op.drop_index(op.f('ix_product_intake_requests_id'), table_name='product_intake_requests')
    op.drop_index(op.f('ix_product_intake_requests_barcode_value'), table_name='product_intake_requests')
    op.create_unique_constraint('product_intake_requests_request_number_key', 'product_intake_requests', ['request_number'])
    op.drop_constraint('uq_barcode_value', 'product_barcodes', type_='unique')
    op.drop_index(op.f('ix_product_barcodes_product_id'), table_name='product_barcodes')
    op.drop_index(op.f('ix_product_barcodes_id'), table_name='product_barcodes')
    op.drop_index(op.f('ix_product_barcodes_barcode_value'), table_name='product_barcodes')
    op.create_unique_constraint('product_barcodes_barcode_value_key', 'product_barcodes', ['barcode_value'])
    op.drop_index(op.f('ix_order_templates_salesman_id'), table_name='order_templates')
    op.drop_index(op.f('ix_order_templates_id'), table_name='order_templates')
    op.alter_column('order_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_order_template_items_id'), table_name='order_template_items')
    op.drop_index(op.f('ix_location_logs_id'), table_name='location_logs')
    op.drop_constraint('uq_brand_normalized', 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.create_table('customer_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer_contacts_customer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='customer_contacts_pkey')
    )
    # ### end Alembic commands ###
