"""add client idempotency keys

Revision ID: b79a4d6bb2cc
Revises: 7d8ed524c8d2
Create Date: 2026-09-09 02:04:41.395184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79a4d6bb2cc'
down_revision: Union[str, None] = '7d8ed524c8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_adjustments', sa.Column('client_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_inventory_adjustments_client_key'), 'inventory_adjustments', ['client_key'], unique=True)
    op.add_column('inventory_receipts', sa.Column('client_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_inventory_receipts_client_key'), 'inventory_receipts', ['client_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_receipts_client_key'), table_name='inventory_receipts')
    op.drop_column('inventory_receipts', 'client_key')
    op.drop_index(op.f('ix_inventory_adjustments_client_key'), table_name='inventory_adjustments')
    op.drop_column('inventory_adjustments', 'client_key')
    # ### end Alembic commands ###
