"""add inventory receiving and unit identity

Revision ID: fbbbc7c03c6a
Revises: c254edd4c4e5
Create Date: 2026-09-08 20:41:48.738247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbbc7c03c6a'
down_revision: Union[str, None] = 'c254edd4c4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('inventory_receipts'):
        op.create_table(
            'inventory_receipts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('receipt_number', sa.String(length=50), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('supplier_name', sa.String(length=200), nullable=True),
            sa.Column('reference_number', sa.String(length=100), nullable=True),
            sa.Column('warehouse_location', sa.String(length=100), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('created_by', sa.Integer(), nullable=False),
            sa.Column('posted_by', sa.Integer(), nullable=True),
            sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['created_by'], ['users.id']),
            sa.ForeignKeyConstraint(['posted_by'], ['users.id']),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('receipt_number'),
        )
        op.create_index('ix_inventory_receipts_id', 'inventory_receipts', ['id'], unique=False)
        op.create_index('ix_inventory_receipts_receipt_number', 'inventory_receipts', ['receipt_number'], unique=True)
        op.create_table(
            'inventory_receipt_lines',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('receipt_id', sa.Integer(), nullable=False),
            sa.Column('product_id', sa.Integer(), nullable=False),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.Column('tracking_mode', sa.String(length=20), nullable=False),
            sa.Column('batch_number', sa.String(length=100), nullable=True),
            sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['product_id'], ['products.id']),
            sa.ForeignKeyConstraint(['receipt_id'], ['inventory_receipts.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index('ix_inventory_receipt_lines_id', 'inventory_receipt_lines', ['id'], unique=False)
        op.create_index('ix_inventory_receipt_lines_receipt_id', 'inventory_receipt_lines', ['receipt_id'], unique=False)
        op.create_index('ix_inventory_receipt_lines_product_id', 'inventory_receipt_lines', ['product_id'], unique=False)
        op.create_table(
            'inventory_receipt_images',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('receipt_id', sa.Integer(), nullable=False),
            sa.Column('file_path', sa.String(length=500), nullable=False),
            sa.Column('original_filename', sa.String(length=255), nullable=True),
            sa.Column('caption', sa.String(length=255), nullable=True),
            sa.Column('uploaded_by', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['receipt_id'], ['inventory_receipts.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['uploaded_by'], ['users.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index('ix_inventory_receipt_images_id', 'inventory_receipt_images', ['id'], unique=False)
        op.create_index('ix_inventory_receipt_images_receipt_id', 'inventory_receipt_images', ['receipt_id'], unique=False)
    op.add_column('product_units', sa.Column('unit_code', sa.String(length=40), nullable=True))
    op.add_column('product_units', sa.Column('manufacturer_serial', sa.String(length=100), nullable=True))
    op.add_column('product_units', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.add_column('product_units', sa.Column('receipt_line_id', sa.Integer(), nullable=True))
    op.drop_index('ix_product_units_barcode', table_name='product_units')
    op.create_index(op.f('ix_product_units_barcode'), 'product_units', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_units_manufacturer_serial'), 'product_units', ['manufacturer_serial'], unique=False)
    op.create_index(op.f('ix_product_units_receipt_id'), 'product_units', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_product_units_receipt_line_id'), 'product_units', ['receipt_line_id'], unique=False)
    op.create_index(op.f('ix_product_units_unit_code'), 'product_units', ['unit_code'], unique=True)
    op.create_foreign_key(None, 'product_units', 'inventory_receipts', ['receipt_id'], ['id'])
    op.create_foreign_key(None, 'product_units', 'inventory_receipt_lines', ['receipt_line_id'], ['id'])
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'category_id')
    op.drop_constraint(None, 'product_units', type_='foreignkey')
    op.drop_constraint(None, 'product_units', type_='foreignkey')
    op.drop_index(op.f('ix_product_units_unit_code'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_receipt_line_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_receipt_id'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_manufacturer_serial'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_barcode'), table_name='product_units')
    op.create_index('ix_product_units_barcode', 'product_units', ['barcode'], unique=False)
    op.drop_column('product_units', 'receipt_line_id')
    op.drop_column('product_units', 'receipt_id')
    op.drop_column('product_units', 'manufacturer_serial')
    op.drop_column('product_units', 'unit_code')
    # ### end Alembic commands ###
